#!/usr/bin/env bash
# Install WALL-ST-E's outbound-only polling executor on Debian/Ubuntu + systemd.
# Dry run is the default. --live is an explicit, locally acknowledged mode.
set -euo pipefail
umask 077

MODE="paper"
SECRET=""
SECRET_FILE=""
JUPITER_KEY=""
JUPITER_KEY_FILE=""
FLOOR=""
MAX_SOL=""
DAILY_CAP=""
DAILY_LOSS_CAP=""
MAX_SOL_SET=0
DAILY_CAP_SET=0
DAILY_LOSS_CAP_SET=0
RPC=""
SECONDARY_RPC=""
RPC_FILE=""
SECONDARY_RPC_FILE=""
SOURCE_DIR=""
SOURCE_COMMIT="remote-paper"
BOOTSTRAP_NODE=0
EXPECTED_COMMIT=""
API="https://claude-company-api.onrender.com"
STATIC="https://claudedotcompany.com"

# BEGIN RELEASE_PRUNER
# Every install leaves a ~136 MB release behind and nothing ever removed one.
# Measured on one host: 28 releases, 3.6 GB. A small VPS is 25 GB, and the journal
# writes with synchronous=FULL — a full disk stops the position book, not merely the
# logs, and it stops it at the moment an exit needs recording.
#
# Keeps: the release `current` points at, the one just installed, and the newest
# KEEP_RELEASES others so the rollback path above still has somewhere to go.
# Touches only real directories directly under the releases dir, never a symlink,
# and never anything outside it. Release names are generated by this script and by
# macos-release.sh, so they contain no spaces or newlines.
prune_releases() {
  local releases_dir="$1" keep_current="$2" keep_new="$3" keep_n="${4:-3}"
  [ -d "$releases_dir" ] || return 0
  local kept=0 dir
  for dir in $(ls -1dt "$releases_dir"/*/ 2>/dev/null); do
    dir="${dir%/}"
    case "$dir" in "$releases_dir"/*) ;; *) continue;; esac
    [ -L "$dir" ] && continue
    [ -d "$dir" ] || continue
    [ "$dir" = "$keep_current" ] && continue
    [ "$dir" = "$keep_new" ] && continue
    kept=$((kept + 1))
    [ "$kept" -le "$keep_n" ] && continue
    rm -rf "$dir"
  done
  return 0
}
# END RELEASE_PRUNER

# BEGIN SYSTEMD_ENV_WRITER
# EnvironmentFile is not a shell script. Quote every value using systemd's
# double-quoted syntax so URLs and credentials containing shell metacharacters are
# stored literally. Newlines cannot exist in a process environment and would also
# turn one assignment into several, so reject them explicitly.
systemd_env_value() {
  local value="$1"
  case "$value" in
    *$'\n'*|*$'\r'*) echo "environment values cannot contain newlines" >&2; return 1;;
  esac
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//\$/\\\$}"
  value="${value//\`/\\\`}"
  printf '"%s"' "$value"
}

write_env_line() {
  local name="$1" value="$2"
  if ! [[ "$name" =~ ^[A-Z_][A-Z0-9_]*$ ]]; then
    echo "invalid environment variable name: $name" >&2
    return 1
  fi
  printf '%s=' "$name"
  systemd_env_value "$value"
  printf '\n'
}
# END SYSTEMD_ENV_WRITER

need_value() {
  if [ "$#" -lt 2 ] || [ -z "$2" ]; then
    echo "missing value for $1" >&2
    exit 1
  fi
}

# BEGIN SYMLINK_ACTIVATION
# Swapping the `current` symlink is the moment the new release becomes the running
# one, so it has to be atomic and it must never follow the link it is replacing.
# GNU mv spells that `mv -T`. BSD/macOS mv has no such flag and does the opposite:
# measured on macOS 15, `mv -f next current` where current -> r1 left current still
# pointing at r1 and moved the new link INSIDE r1. Silent, and it would leave a Mac
# install running last week's code with no error anywhere.
#
# rename(2) is atomic and never dereferences either operand on any Unix, and this
# installer has already verified a Node it can call. One code path, both platforms.
activate_symlink() {
  LINK_FROM="$1" LINK_TO="$2" "${NODE_BIN:-node}" -e \
    'require("fs").renameSync(process.env.LINK_FROM, process.env.LINK_TO)'
}
# END SYMLINK_ACTIVATION

# BEGIN HELP
# There was no --help at all. The one-line curl install makes that a real hole: a
# user who pipes an unknown script into bash and cannot ask it what it does has no
# way to find out except reading 700 lines of shell. The first paragraph therefore
# answers the only question that matters — does this spend my money — before it
# lists a single flag. Kept inside 80 columns so it survives a default terminal.
usage() {
  cat <<'HELP'
Usage: bash install.sh --floor N [options]

Installs WALL-ST-E, your floor's self-hosted trading executor, as a supervised
background service on this machine. Linux hosts get a hardened systemd unit;
macOS hosts get a per-user launchd LaunchAgent. Everything before that last
step — Node, the burner wallet, the secret prompt, the staged release — is one
shared path on both.

THE DEFAULT IS A DRY RUN. Without --live the executor reads your floor's call
feed and runs the entire local policy WITHOUT signing or submitting anything.
It trades no money at all. Going live is a separate, deliberate act: --live
makes you retype the burner wallet's own public key on this terminal before
the service is armed, and raising any cap makes you type a second sentence.

This installer never funds a wallet. It generates a dedicated burner keypair
on THIS machine at $HOME/claudeco-executor/burner.json (mode 0600) and never
transmits it anywhere. Back that file up before you fund it: it exists on this
disk and nowhere else.

The floor feed secret is NEVER a command-line flag, because argv lands in your
shell history and in the process list. It is read hidden from /dev/tty, or
from a mode-0600 file you name with --secret-file.

Options:
  --floor N             Required. Your floor number, as shown by the panel.
  --secret-file FILE    Mode-0600 file holding the floor feed secret, for an
                        unattended install. Otherwise prompted on the tty.
  --live                Arm real mainnet trading. Not the default. Needs two
                        independent private RPCs, a Jupiter key, a pinned
                        local checkout, and a typed acknowledgement.
  --rpc-file FILE       Mode-0600 file holding the primary Solana RPC URL.
  --secondary-rpc-file FILE
                        Mode-0600 file holding a SECOND RPC URL from a
                        DIFFERENT provider. The executor cross-checks the two
                        and refuses to act on one provider's word alone.
  --jupiter-key-file FILE
                        Mode-0600 file holding your Jupiter API key.
  --rpc URL             Same values inline. They land in shell history, so a
  --secondary-rpc URL   live install should prefer the --*-file forms above.
  --max-sol SOL         Live cap per trade. Canary default 0.005.
  --daily-cap SOL       Live rolling-24h deployment cap. Default 0.01.
  --daily-loss-cap SOL  Live rolling-24h realized-loss entry brake. 0.01.
                        Raising any one of these three requires all three
                        together plus a second typed acknowledgement.
  --source-dir DIR      The executor directory of a pinned local checkout.
                        Required by --live: live never runs downloaded code.
  --expected-commit SHA The exact 40-character published commit. Required by
                        --live, and it must match the checkout's HEAD.
  --bootstrap-node      Accept the private Node install without being asked.
  --api URL             Claude Company API base.
  --static URL          Static base for the paper-mode runtime download.
  --help                Print this and exit 0.

Live install with a terminal and no credential files: the installer walks you
through each of the primary RPC, the secondary RPC and the Jupiter key. It
explains each one, reads it hidden from /dev/tty, checks it against the
provider before accepting it, and stores it mode 0600 under
$HOME/claudeco-executor so the next run can be unattended.

Node >=22.13 and <25 is required for the durable SQLite journal. If this host
has no Node in that range, the installer offers to download the pinned build,
verify it against nodejs.org's own SHASUMS256.txt, and unpack a private copy
under the install directory. No sudo, no shell profile is edited, and any
system Node is left exactly as it is.

On macOS the service is a per-user LaunchAgent (com.claudeco.wallste) installed
and started by the project's own macos-launchagent.sh, which this installer
invokes rather than reimplementing. No sudo is used anywhere on that path. A
--live install on a Mac additionally goes through macos-release.sh, which
stages an immutable, commit-named release and runs its test suite first.

Windows is not supported directly. Install Ubuntu under WSL2 and run this
inside that Ubuntu shell; see the Windows section of executor/README.md.
HELP
}
# END HELP

while [ "$#" -gt 0 ]; do
  case "$1" in
    --help|-h) usage; exit 0;;
    --live) MODE="live"; shift;;
    --secret-file) need_value "$@"; SECRET_FILE="$2"; shift 2;;
    --jupiter-key-file) need_value "$@"; JUPITER_KEY_FILE="$2"; shift 2;;
    --floor) need_value "$@"; FLOOR="$2"; shift 2;;
    --max-sol) need_value "$@"; MAX_SOL="$2"; MAX_SOL_SET=1; shift 2;;
    --daily-cap) need_value "$@"; DAILY_CAP="$2"; DAILY_CAP_SET=1; shift 2;;
    --daily-loss-cap) need_value "$@"; DAILY_LOSS_CAP="$2"; DAILY_LOSS_CAP_SET=1; shift 2;;
    --rpc) need_value "$@"; RPC="$2"; shift 2;;
    --rpc-file) need_value "$@"; RPC_FILE="$2"; shift 2;;
    --secondary-rpc) need_value "$@"; SECONDARY_RPC="$2"; shift 2;;
    --secondary-rpc-file) need_value "$@"; SECONDARY_RPC_FILE="$2"; shift 2;;
    --source-dir) need_value "$@"; SOURCE_DIR="$2"; shift 2;;
    # ${x,,} is bash 4. macOS ships /bin/bash 3.2, where that expansion is a "bad
    # substitution" at runtime, so the whole installer would die on a Mac the moment
    # anyone passed this flag. printf is a builtin and tr sees only its own two
    # patterns in argv.
    --expected-commit) need_value "$@"; EXPECTED_COMMIT="$(printf '%s' "$2" | tr '[:upper:]' '[:lower:]')"; shift 2;;
    --api) need_value "$@"; API="$2"; shift 2;;
    --static) need_value "$@"; STATIC="$2"; shift 2;;
    --bootstrap-node) BOOTSTRAP_NODE=1; shift;;
    *) echo "unknown flag: $1" >&2; exit 1;;
  esac
done

# BEGIN PLATFORM_GUIDANCE
# Git Bash, MSYS2 and Cygwin all report a uname of MINGW64_NT-10.0 / MSYS_NT-10.0 /
# CYGWIN_NT-10.0. They have neither systemd nor launchd, so the generic "Linux hosts
# using systemd only" line below reads to a Windows user as a broken script rather
# than as the missing prerequisite it actually is. Name the supported route and the
# exact commands instead: WSL2 is a supported Linux host, and the same one-liner
# works verbatim once they are inside the Ubuntu shell.
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*|Windows_NT)
    cat >&2 <<'WSL'

WALL-ST-E cannot run in Git Bash, MSYS2 or Cygwin: it installs a systemd service,
and Windows has no systemd. Use WSL2 — it is a real Linux host and the installer
runs there unchanged.

In PowerShell, as Administrator, once:

    wsl --install -d Ubuntu

Reboot if it asks, then open the "Ubuntu" app from the Start menu and run, inside
that Ubuntu shell (not PowerShell, not Git Bash):

    sudo apt-get update && sudo apt-get install -y curl
    curl -fsSL https://claudedotcompany.com/install.sh | bash -s -- --floor N

Replace N with your floor number. That install is still a dry run and trades
nothing. Keep the Ubuntu window open: closing it stops WSL2, and a stopped WSL2
stops the executor.
WSL
    exit 1;;
esac

# macOS is a first-class target, not a redirect to somebody else's computer. It was
# refused here until 2026-09-06 even though every piece already existed and shipped:
# macos-launchagent.sh renders, installs and loads the LaunchAgent, and
# launchd-runner.mjs validates the environment and runtime it is handed. What was
# missing was only this orchestration — so PLATFORM selects a supervisor below and
# everything up to that point (Node, secret, caps, staging, burner, environment) is
# one shared path with one set of guarantees.
PLATFORM=""
case "$(uname -s)" in
  Linux)
    if ! command -v systemctl >/dev/null 2>&1; then
      echo "this Linux host has no systemd; install.sh supervises Linux through systemd" >&2
      echo "a container or chroot without systemd is not a supported executor host" >&2
      exit 1
    fi
    PLATFORM="linux";;
  Darwin) PLATFORM="darwin";;
  *)
    echo "install.sh supports Linux (systemd) and macOS (launchd); this host reports $(uname -s)" >&2
    exit 1;;
esac
# END PLATFORM_GUIDANCE

# stat(1) is not portable: coreutils spells the permission bits -c '%a' and BSD/macOS
# spells them -f '%Lp'. GNU stat also ACCEPTS -f (it means "filesystem" there) and
# exits 0 printing something else entirely, so probing by trial silently returns a
# wrong mode on Linux. Branch on the platform that was just determined instead.
file_mode() {
  if [ "$PLATFORM" = "darwin" ]; then stat -f '%Lp' "$1"; else stat -c '%a' "$1"; fi
}
case "$FLOOR" in
  ""|*[!0-9]*) echo "--floor must be a positive integer" >&2; exit 1;;
esac
if [ "$FLOOR" -le 0 ]; then echo "--floor must be a positive integer" >&2; exit 1; fi

# These paths used to be defined 200 lines lower, immediately before the Node check.
# They moved up because two things that now run early need them: the private Node
# bootstrap unpacks under $INSTALL_DIR, and the credential wizard writes its 0600
# files there. Nothing here creates anything; only the blocks that need a directory
# make one.
INSTALL_DIR="$HOME/claudeco-executor"
ENV_FILE="$INSTALL_DIR/.cc-executor.env"
STATE_DB="$INSTALL_DIR/.cc-executor.sqlite"
LOCK_FILE="${STATE_DB}.lock"
PAUSE_FILE="$INSTALL_DIR/PAUSE_ENTRIES"
HARD_STOP_FILE="$INSTALL_DIR/HARD_STOP"
RELEASES_DIR="$INSTALL_DIR/releases"
CURRENT_LINK="$INSTALL_DIR/current"
NODE_RUNTIME_DIR="$INSTALL_DIR/runtime"
SERVICE_FILE="/etc/systemd/system/cc-executor.service"
# macos-release.sh owns its own immutable, commit-named release tree and must never
# share one with the pruner above: prune_releases keeps `current`, the new release and
# the newest few, and would happily delete a versioned release it does not know about.
VERSIONED_RELEASES_DIR="$INSTALL_DIR/versioned-releases"
LAUNCHD_LABEL="com.claudeco.wallste"
echo "▶ installing WALL-ST-E ($MODE mode) into $INSTALL_DIR"
if [ "$PLATFORM" = "darwin" ]; then
  echo "  supervisor: launchd (per-user LaunchAgent $LAUNCHD_LABEL)"
else
  echo "  supervisor: systemd (system unit cc-executor)"
fi

# BEGIN NODE_FETCH
# Node >=22.13 and <25 is the durable-journal requirement (node:sqlite's
# DatabaseSync). A host without it used to be a dead end: one line of stderr and an
# exit, which is where most non-technical owners stopped. Offer a PRIVATE copy
# instead — official bytes, a pinned version, checksum-verified before anything is
# unpacked, living under the install directory and used by this executor only.
# No sudo, no package manager, no profile edited, and nothing piped into a shell.
NODE_PINNED_VERSION="22.23.2"
# Pinned deliberately, never resolved through a "latest" alias: an alias lets the far
# end choose which bytes you end up verifying, and the checksum would then prove only
# that the download arrived intact. Bumping this is a one-line, reviewable edit.
# NODE_DIST_BASE is overridable so the regression test can drive this whole function
# against a local file:// mirror; anyone who can set this process's environment can
# already replace the script itself, so it grants nothing new.
NODE_DIST_BASE="${NODE_DIST_BASE:-https://nodejs.org/dist}"

node_version_ok() {
  "$1" -e 'const [a,b]=process.versions.node.split(".").map(Number); process.stdout.write(String(a<25&&(a>22||(a===22&&b>=13))?1:0))' 2>/dev/null || printf 0
}

# One digest helper, three possible providers: sha256sum is coreutils (the Linux
# target), shasum ships with macOS, openssl is the last resort. A host with none of
# them must not be allowed to silently skip verification.
sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  elif command -v openssl >/dev/null 2>&1; then openssl dgst -sha256 "$1" | awk '{print $NF}'
  else echo "no sha256 tool (sha256sum, shasum or openssl) is available" >&2; return 1
  fi
}

# Downloads, verifies and unpacks exactly one official Node build. The resulting
# absolute node path goes to stdout; every human-facing line goes to stderr, so the
# caller can capture the path with a command substitution and still show the work.
install_private_node() {
  local version="$1" root="$2"
  local os arch ext tarball url expected actual work dir
  case "$(uname -s)" in
    Linux) os="linux";;
    Darwin) os="darwin";;
    *) echo "there is no official Node build for $(uname -s)" >&2; return 1;;
  esac
  case "$(uname -m)" in
    x86_64|amd64) arch="x64";;
    aarch64|arm64) arch="arm64";;
    armv7l) arch="armv7l";;
    *) echo "there is no official Node build for CPU $(uname -m)" >&2; return 1;;
  esac
  # .tar.xz is what nodejs.org leads with and is half the size, but a minimal
  # container may have no xz. The .gz is listed in the same SHASUMS256.txt and
  # verifies by exactly the same rule, so falling back costs no assurance.
  if command -v xz >/dev/null 2>&1; then ext="tar.xz"; else ext="tar.gz"; fi
  tarball="node-v$version-$os-$arch.$ext"
  url="$NODE_DIST_BASE/v$version/$tarball"
  work="$(mktemp -d "$root/.node-download.XXXXXXXX")" || return 1
  echo "▶ fetching official Node v$version ($os-$arch) from $NODE_DIST_BASE" >&2
  if ! curl -fsSL "$NODE_DIST_BASE/v$version/SHASUMS256.txt" -o "$work/SHASUMS256.txt"; then
    echo "could not download SHASUMS256.txt for Node v$version" >&2
    rm -rf "$work"; return 1
  fi
  if ! curl -fsSL "$url" -o "$work/$tarball"; then
    echo "could not download $tarball" >&2
    rm -rf "$work"; return 1
  fi
  # Lines are "<64 hex><two spaces><filename>". Match the filename field exactly:
  # a substring match would happily accept the row for node-...tar.gz.asc.
  expected="$(awk -v want="$tarball" '$2 == want { print $1 }' "$work/SHASUMS256.txt" | head -n 1)"
  actual="$(sha256_of "$work/$tarball")" || { rm -rf "$work"; return 1; }
  echo "  published sha256: ${expected:-<no such filename in SHASUMS256.txt>}" >&2
  echo "  downloaded sha256: $actual" >&2
  if [ -z "$expected" ] || [ "$expected" != "$actual" ]; then
    cat >&2 <<'MISMATCH'

  ✗ CHECKSUM MISMATCH — refusing to install this Node.
    The bytes that arrived are not the bytes nodejs.org published for this exact
    version. That is a truncated transfer, a caching proxy serving something else,
    or a middlebox rewriting the download. Nothing was unpacked and nothing ran.
    Retry on another network, or install Node yourself from a source you trust.
MISMATCH
    rm -rf "$work"; return 1
  fi
  echo "  ✓ checksum matches the published SHASUMS256.txt" >&2
  if ! tar -xf "$work/$tarball" -C "$work"; then
    echo "could not unpack $tarball" >&2
    rm -rf "$work"; return 1
  fi
  dir="$root/node-v$version-$os-$arch"
  rm -rf "$dir"
  if [ ! -x "$work/node-v$version-$os-$arch/bin/node" ]; then
    echo "the verified archive did not contain node-v$version-$os-$arch/bin/node" >&2
    rm -rf "$work"; return 1
  fi
  mv "$work/node-v$version-$os-$arch" "$dir" || { rm -rf "$work"; return 1; }
  rm -rf "$work"
  printf '%s\n' "$dir/bin/node"
}
# END NODE_FETCH

NODE_BIN=""
NODE_PRIVATE=0
node_ok=0
if command -v node >/dev/null 2>&1; then
  NODE_BIN="$(command -v node)"
  node_ok="$(node_version_ok "$NODE_BIN")"
fi
if [ "$node_ok" != "1" ]; then
  # A previous run of this installer may already have bootstrapped one. Adopt it
  # rather than downloading it again; the version is pinned, so this is the same
  # binary the checksum already accepted.
  for node_candidate in "$NODE_RUNTIME_DIR"/node-v*/bin/node; do
    if [ -x "$node_candidate" ] && [ "$(node_version_ok "$node_candidate")" = "1" ]; then
      NODE_BIN="$node_candidate"; NODE_PRIVATE=1; node_ok=1; break
    fi
  done
fi
if [ "$node_ok" != "1" ]; then
  node_found="none on PATH"
  if command -v node >/dev/null 2>&1; then node_found="$(node --version 2>/dev/null || echo unknown)"; fi
  echo "Node >=22.13 and <25 is required for the durable SQLite journal; this host has: $node_found"
  node_accept="$BOOTSTRAP_NODE"
  if [ "$node_accept" != "1" ]; then
    if [ ! -r /dev/tty ]; then
      echo "no terminal to ask on; rerun with --bootstrap-node to install a private Node v$NODE_PINNED_VERSION under $NODE_RUNTIME_DIR, or install Node yourself from a package source you trust" >&2
      exit 1
    fi
    cat > /dev/tty <<TTY

  I can install a PRIVATE copy of Node for this executor only:
    · the official build node-v$NODE_PINNED_VERSION-<your platform> from $NODE_DIST_BASE
    · verified against nodejs.org's own SHASUMS256.txt before anything is unpacked
    · unpacked into $NODE_RUNTIME_DIR and used only by this service
    · no sudo, no package manager, no shell profile edited
    · any Node already on this machine is left exactly as it is
TTY
    printf "  Install that private Node now? [Y/n] " > /dev/tty
    IFS= read -r node_answer < /dev/tty
    case "$node_answer" in ""|y|Y|yes|Yes|YES) node_accept=1;; *) node_accept=0;; esac
  fi
  if [ "$node_accept" != "1" ]; then
    echo "declined; install Node >=22.13 and <25 from a package source you trust, then rerun" >&2
    exit 1
  fi
  mkdir -p "$NODE_RUNTIME_DIR"
  chmod 700 "$INSTALL_DIR" "$NODE_RUNTIME_DIR"
  NODE_BIN="$(install_private_node "$NODE_PINNED_VERSION" "$NODE_RUNTIME_DIR")" || {
    echo "private Node bootstrap failed; install Node >=22.13 and <25 yourself and rerun" >&2
    exit 1
  }
  node_ok="$(node_version_ok "$NODE_BIN")"
  if [ "$node_ok" != "1" ]; then
    echo "the bootstrapped Node reports $("$NODE_BIN" --version 2>/dev/null) which is outside >=22.13 and <25" >&2
    exit 1
  fi
  NODE_PRIVATE=1
fi
if [ "$NODE_PRIVATE" -eq 1 ]; then
  # Every later node/npm in THIS process must be the runtime systemd's ExecStart will
  # use — npm ci resolves native builds against the running node. This assignment
  # lives and dies with this process: no profile, no /usr/local, no login shell, and
  # nothing on disk outside $INSTALL_DIR is touched.
  PATH="$(cd "$(dirname "$NODE_BIN")" && pwd -P):$PATH"
  export PATH
  echo "  ✓ private Node $("$NODE_BIN" --version) at $NODE_BIN"
  echo "    Your login PATH and any system Node are untouched."
fi

read_private_file() {
  local label="$1" file="$2" mode
  if [ ! -f "$file" ] || [ ! -r "$file" ] || [ -L "$file" ]; then
    echo "$label file is not a readable regular non-symlink file: $file" >&2
    exit 1
  fi
  mode="$(file_mode "$file")"
  if (( (8#$mode & 8#077) != 0 )); then
    echo "$label file must not be accessible by group/other (chmod 600 $file)" >&2
    exit 1
  fi
  IFS= read -r REPLY < "$file" || true
}

if [ -n "$RPC_FILE" ]; then
  if [ -n "$RPC" ]; then echo "use either --rpc or --rpc-file, not both" >&2; exit 1; fi
  read_private_file "primary RPC" "$RPC_FILE"
  RPC="$REPLY"
fi
if [ -n "$SECONDARY_RPC_FILE" ]; then
  if [ -n "$SECONDARY_RPC" ]; then
    echo "use either --secondary-rpc or --secondary-rpc-file, not both" >&2
    exit 1
  fi
  read_private_file "secondary RPC" "$SECONDARY_RPC_FILE"
  SECONDARY_RPC="$REPLY"
fi

# A file-based invocation from a checked-out release automatically stages the five
# sibling runtime modules. Piped execution has no trusted sibling directory and is
# therefore never accepted for live signing.
if [ -z "$SOURCE_DIR" ] && [ -f "${BASH_SOURCE[0]:-}" ]; then
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
  if [ -f "$script_dir/poller.mjs" ] && [ -f "$script_dir/package-lock.json" ]; then
    SOURCE_DIR="$script_dir"
  fi
fi
if [ -n "$SOURCE_DIR" ]; then
  SOURCE_DIR="$(cd "$SOURCE_DIR" && pwd -P)"
fi
if [ "$MODE" = "live" ] && [ -z "$SOURCE_DIR" ]; then
  echo "live mode requires --source-dir from a locally pinned Claude Company checkout" >&2
  exit 1
fi
if [ "$MODE" = "live" ]; then
  if ! command -v git >/dev/null 2>&1 ||
     ! source_root="$(git -C "$SOURCE_DIR" rev-parse --show-toplevel 2>/dev/null)"; then
    echo "live source must be inside a Git checkout" >&2
    exit 1
  fi
  source_root="$(cd "$source_root" && pwd -P)"
  if [ "$SOURCE_DIR" != "$source_root/executor" ]; then
    echo "live --source-dir must be the checkout's executor directory" >&2
    exit 1
  fi
  if git -C "$source_root" symbolic-ref -q HEAD >/dev/null 2>&1; then
    echo "live source must be detached at the published commit, not a moving branch" >&2
    exit 1
  fi
  SOURCE_COMMIT="$(git -C "$source_root" rev-parse HEAD)"
  if ! [[ "$SOURCE_COMMIT" =~ ^[0-9a-f]{40}$ ]]; then
    echo "live source commit is invalid" >&2
    exit 1
  fi
  if ! [[ "$EXPECTED_COMMIT" =~ ^[0-9a-f]{40}$ ]] || [ "$EXPECTED_COMMIT" != "$SOURCE_COMMIT" ]; then
    echo "live --expected-commit must exactly match the published commit $SOURCE_COMMIT" >&2
    exit 1
  fi
  for source_file in poller.mjs burner-backup.mjs journal.mjs jupiter.mjs token2022.mjs balance-verification.mjs entry-quote-guard.mjs exit-trigger.mjs feed-drain.mjs sol-usd-oracle.mjs heartbeat-health.mjs sleep-assertion.mjs monitor.mjs strategy.mjs trade-policy.mjs entry-contract.mjs dexscreener-consensus.mjs desk-mirror.mjs package.json package-lock.json; do
    if [ -n "$(git -C "$source_root" status --porcelain -- "executor/$source_file")" ]; then
      echo "live source file executor/$source_file differs from commit $SOURCE_COMMIT" >&2
      exit 1
    fi
  done
elif [ -n "$SOURCE_DIR" ] && command -v git >/dev/null 2>&1; then
  SOURCE_COMMIT="$(git -C "$SOURCE_DIR" rev-parse HEAD 2>/dev/null || echo local-paper)"
fi

if [ -n "$SECRET_FILE" ]; then
  read_private_file "floor secret" "$SECRET_FILE"
  SECRET="$REPLY"
else
  if [ ! -r /dev/tty ]; then
    echo "no terminal available; pass --secret-file with a mode-0600 file" >&2
    exit 1
  fi
  printf "Claude Company executor feed secret: " > /dev/tty
  IFS= read -r -s SECRET < /dev/tty
  printf "\n" > /dev/tty
fi
case "$SECRET" in
  ""|*[!0-9A-Fa-f]*) echo "floor secret must be the hex value shown by the executor panel" >&2; exit 1;;
esac
if [ "${#SECRET}" -lt 32 ]; then echo "floor secret is unexpectedly short" >&2; exit 1; fi

# BEGIN CREDENTIAL_WIZARD
# Three absolute paths to files the owner had to create first, from services they had
# to go and find, is where every non-scripted live install stopped. The flags below
# still work byte-for-byte for automation; this only fills in what is missing when a
# human is actually sitting at a terminal. Every value is read hidden, checked
# against the real provider BEFORE it is accepted, and written 0600 — so the next run
# of the installer is unattended without the owner ever handling a path by hand.
CRED_WSOL="So11111111111111111111111111111111111111112"
CRED_USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
CRED_JUPITER_BASE="${CRED_JUPITER_BASE:-https://api.jup.ag/swap/v2}"

cred_escape() {
  # curl's config format takes double-quoted values with backslash escapes.
  local value="$1"
  value="${value//\\/\\\\}"
  printf '%s' "${value//\"/\\\"}"
}

cred_curl() {
  # An RPC URL carries its API key in the path, and a Jupiter key is a header. Both
  # would be world-readable in /proc/PID/cmdline for the life of the request if they
  # were passed as curl arguments, on exactly the kind of shared host this installs
  # on. curl --config - takes the whole request on stdin instead, which never becomes
  # argv. stderr is folded in so the provider's (or curl's) own words survive.
  local url="$1"; shift
  local line
  {
    printf 'url = "%s"\n' "$(cred_escape "$url")"
    printf 'silent\nshow-error\nmax-time = "20"\nwrite-out = "\\n%%{http_code}"\n'
    for line in "$@"; do printf '%s\n' "$line"; done
  } | curl --config - 2>&1
}

cred_report() {
  # The endpoint is never echoed — it IS the credential. Only the far end's answer.
  local status="$1" body="$2"
  case "$status" in
    ''|*[!0-9]*|000) status="no HTTP response";;
    *) status="HTTP $status";;
  esac
  printf '     rejected — %s: %s\n' "$status" \
    "$(printf '%s' "$body" | tr '\r\n' '  ' | cut -c1-200)" >&2
}

cred_probe_rpc() {
  # getLatestBlockhash is the cheapest call that proves all three things at once: the
  # host answers, the key on it is accepted, and what answers speaks Solana JSON-RPC.
  # getHealth alone returns a bare "ok" that a misconfigured proxy can also produce.
  local out status body
  out="$(cred_curl "$1" 'request = "POST"' 'header = "content-type: application/json"' \
    'data = "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getLatestBlockhash\",\"params\":[{\"commitment\":\"confirmed\"}]}"')"
  status="$(printf '%s' "$out" | tail -n 1)"
  body="$(printf '%s' "$out" | sed '$d')"
  case "$status" in ''|*[!0-9]*) body="$out"; status="";; esac
  if [ "$status" = "200" ] && printf '%s' "$body" | grep -q '"blockhash"'; then
    return 0
  fi
  cred_report "$status" "$body"
  return 1
}

cred_probe_jupiter() {
  # A taker-less /order is a price quote: it authenticates the key, costs nothing,
  # names no wallet and cannot be signed. Same host and same header the executor uses.
  local out status body
  out="$(cred_curl "$CRED_JUPITER_BASE/order?inputMint=$CRED_WSOL&outputMint=$CRED_USDC&amount=1000000&swapMode=ExactIn&slippageBps=300" \
    "header = \"x-api-key: $(cred_escape "$1")\"")"
  status="$(printf '%s' "$out" | tail -n 1)"
  body="$(printf '%s' "$out" | sed '$d')"
  case "$status" in ''|*[!0-9]*) body="$out"; status="";; esac
  if [ "$status" = "200" ] && printf '%s' "$body" | grep -q '"outAmount"'; then
    return 0
  fi
  cred_report "$status" "$body"
  return 1
}

cred_check_rpc() {
  local endpoint="$1" lowered
  case "$endpoint" in https://*) ;; *) echo "     must be a full https:// URL." >&2; return 1;; esac
  case "$endpoint" in *$'\n'*|*$'\r'*) echo "     contains a line break." >&2; return 1;; esac
  # ${x,,} is bash 4 and this block is also driven by the regression test on macOS,
  # whose /bin/bash is 3.2. printf is a builtin and tr only ever sees its own two
  # patterns in argv, so the endpoint never becomes another process's argument.
  lowered="$(printf '%s' "$endpoint" | tr '[:upper:]' '[:lower:]')"
  case "$lowered" in *api.mainnet-beta.solana.com*)
    echo "     that is the free public Solana endpoint. It rate-limits precisely when everyone else is also trading, which is when an exit has to go through. Use a private provider." >&2
    return 1;;
  esac
  cred_probe_rpc "$endpoint"
}

cred_check_jupiter() {
  [ -n "$1" ] || { echo "     nothing entered." >&2; return 1; }
  cred_probe_jupiter "$1"
}

cred_prompt_hidden() {
  # Hidden, from the controlling terminal, exactly like the feed secret above. Never
  # echoed, never in argv, and the caller must not print CRED_VALUE either.
  printf '  %s: ' "$1" > /dev/tty
  IFS= read -r -s CRED_VALUE < /dev/tty
  printf '\n' > /dev/tty
}

cred_collect() {
  # $1 prompt, $2 validator function, $3 a value to refuse as a duplicate (or "").
  # Result in CRED_VALUE. Three attempts, then fail closed: an install loop that
  # never ends is worse than one that stops and tells you what the provider said.
  local label="$1" validator="$2" forbid="${3:-}" attempt=1
  CRED_VALUE=""
  while [ "$attempt" -le 3 ]; do
    cred_prompt_hidden "$label"
    if [ -z "$CRED_VALUE" ]; then
      echo "     nothing entered." >&2
    elif [ -n "$forbid" ] && [ "$CRED_VALUE" = "$forbid" ]; then
      echo "     that is the primary endpoint again. A second copy of the first provider cross-checks nothing." >&2
    elif "$validator" "$CRED_VALUE"; then
      return 0
    fi
    attempt=$((attempt + 1))
    if [ "$attempt" -le 3 ]; then echo "     let's try again (attempt $attempt of 3)." >&2; fi
  done
  CRED_VALUE=""
  return 1
}

cred_store() {
  # install -m 600 /dev/null creates the file at the final mode BEFORE a single byte
  # of the credential is in it. Writing first and chmod-ing afterwards leaves a real
  # window in which the value sits there at whatever the umask happened to be.
  local file="$1" value="$2"
  mkdir -p "$INSTALL_DIR"
  chmod 700 "$INSTALL_DIR"
  install -m 600 /dev/null "$file"
  printf '%s\n' "$value" > "$file"
  chmod 600 "$file"
}
# END CREDENTIAL_WIZARD

# BEGIN LIVE_CREDENTIALS
if [ "$MODE" = "live" ]; then
  # Announce the wizard only when one is actually about to run. Inline --rpc values
  # leave RPC_FILE empty yet need no prompt, and a banner with nothing behind it is
  # how an installer teaches people to stop reading it.
  if { [ -z "$RPC" ] || [ -z "$SECONDARY_RPC" ] || [ -z "$JUPITER_KEY_FILE" ]; } &&
     [ -r /dev/tty ]; then
    cat > /dev/tty <<'WIZARD'

  LIVE CREDENTIALS
  Three values are needed before this wallet can trade. Each one is read hidden,
  checked against the provider before it is accepted, and saved mode 0600 under
  the install directory so you never do this twice. Nothing is displayed back.
WIZARD
  fi

  if [ -z "$RPC" ]; then
    if [ ! -r /dev/tty ]; then
      echo "--live requires --rpc-file and --secondary-rpc-file so credentials stay out of argv/history, and there is no terminal here for the guided setup" >&2
      exit 1
    fi
    cat > /dev/tty <<'WIZARD'

  1/3  PRIMARY SOLANA RPC
  How this machine reads the chain and sends transactions. The free public
  endpoint will not do: it throttles hardest when everyone is trading, which is
  when an exit has to land. A free private tier is enough to start —
  helius.dev, quicknode.com, alchemy.com and triton.one all have one.
  Paste the full https:// URL including its key.
WIZARD
    cred_collect "Primary RPC URL (hidden)" cred_check_rpc ||
      { echo "no working primary RPC after 3 attempts; nothing was installed" >&2; exit 1; }
    RPC="$CRED_VALUE"
    RPC_FILE="$INSTALL_DIR/.rpc-primary"
    cred_store "$RPC_FILE" "$RPC"
    CRED_VALUE=""
    echo "  ✓ primary RPC answered getLatestBlockhash · stored 0600 at $RPC_FILE" > /dev/tty
  fi

  if [ -z "$SECONDARY_RPC" ]; then
    if [ ! -r /dev/tty ]; then
      echo "--live requires --rpc-file and --secondary-rpc-file so credentials stay out of argv/history, and there is no terminal here for the guided setup" >&2
      exit 1
    fi
    cat > /dev/tty <<'WIZARD'

  2/3  SECONDARY SOLANA RPC — FROM A DIFFERENT PROVIDER
  This is not a spare. Before it acts, the executor asks BOTH endpoints and
  compares the answers: wallet balances, whether a transaction really landed,
  and what a position is currently worth. If the two disagree it refuses to
  trade rather than act on one provider's word. One provider serving a stale
  or wrong answer therefore cannot move your money on its own — which is why a
  second key from the same company would buy you nothing.
  Use a different company from the one above. A free tier is fine.
WIZARD
    cred_collect "Secondary RPC URL (hidden)" cred_check_rpc "$RPC" ||
      { echo "no working secondary RPC after 3 attempts; nothing was installed" >&2; exit 1; }
    SECONDARY_RPC="$CRED_VALUE"
    SECONDARY_RPC_FILE="$INSTALL_DIR/.rpc-secondary"
    cred_store "$SECONDARY_RPC_FILE" "$SECONDARY_RPC"
    CRED_VALUE=""
    echo "  ✓ secondary RPC answered getLatestBlockhash · stored 0600 at $SECONDARY_RPC_FILE" > /dev/tty
  fi

  if [ -n "$JUPITER_KEY_FILE" ]; then
    read_private_file "Jupiter API key" "$JUPITER_KEY_FILE"
    JUPITER_KEY="$REPLY"
  else
    if [ ! -r /dev/tty ]; then
      echo "live mode needs --jupiter-key-file when no terminal is available" >&2
      exit 1
    fi
    cat > /dev/tty <<'WIZARD'

  3/3  JUPITER API KEY
  Jupiter is the router that prices a swap and builds the transaction this
  wallet signs. Get a key at portal.jup.ag; the free tier covers a canary.
  It is checked with a price quote — no wallet is named and nothing can be
  signed by that call.
WIZARD
    cred_collect "Jupiter API key (hidden)" cred_check_jupiter ||
      { echo "the Jupiter key was not accepted after 3 attempts; nothing was installed" >&2; exit 1; }
    JUPITER_KEY="$CRED_VALUE"
    JUPITER_KEY_FILE="$INSTALL_DIR/.jupiter-key"
    cred_store "$JUPITER_KEY_FILE" "$JUPITER_KEY"
    CRED_VALUE=""
    echo "  ✓ Jupiter key returned a live quote · stored 0600 at $JUPITER_KEY_FILE" > /dev/tty
  fi

  if [ -z "$JUPITER_KEY" ]; then echo "Jupiter API key is empty" >&2; exit 1; fi
  if [ -z "$RPC_FILE" ] || [ -z "$SECONDARY_RPC_FILE" ]; then
    echo "--live requires --rpc-file and --secondary-rpc-file so credentials stay out of argv/history" >&2
    exit 1
  fi
  if [ -z "$RPC" ] || [ -z "$SECONDARY_RPC" ]; then
    echo "both live RPC credential files must contain a private HTTPS endpoint" >&2
    exit 1
  fi
  if [ "$SECONDARY_RPC" = "$RPC" ]; then
    echo "--secondary-rpc must be independent from --rpc" >&2
    exit 1
  fi
fi
# END LIVE_CREDENTIALS

# BEGIN LIVE_CAPS_VALIDATOR
LIVE_CANARY_MAX_SOL="0.005"
LIVE_CANARY_DAILY_CAP="0.01"
LIVE_CANARY_DAILY_LOSS_CAP="0.01"
LIVE_MIN_MONEY_CAP="0.000001"
LIVE_OPERATOR_MAX_SOL="0.4"
LIVE_OPERATOR_MAX_DAILY_CAP="1000"
LIVE_OPERATOR_MAX_DAILY_LOSS_CAP="0.4"

if [ -z "$MAX_SOL" ]; then [ "$MODE" = "live" ] && MAX_SOL="$LIVE_CANARY_MAX_SOL" || MAX_SOL="0.05"; fi
if [ -z "$DAILY_CAP" ]; then [ "$MODE" = "live" ] && DAILY_CAP="$LIVE_CANARY_DAILY_CAP" || DAILY_CAP="0.5"; fi
if [ -z "$DAILY_LOSS_CAP" ]; then
  [ "$MODE" = "live" ] && DAILY_LOSS_CAP="$LIVE_CANARY_DAILY_LOSS_CAP" || DAILY_LOSS_CAP="0.15"
fi
# One SOL has exactly 1e9 lamports. Limiting cap literals to that precision keeps
# the comparison exact enough for the declared unit and prevents awk's binary
# floating-point conversion from rounding a mathematically out-of-range literal
# onto an accepted boundary.
number_re='^(0|[1-9][0-9]*)([.][0-9]{1,9})?$'
if ! [[ "$MAX_SOL" =~ $number_re ]] || ! [[ "$DAILY_CAP" =~ $number_re ]] ||
   ! [[ "$DAILY_LOSS_CAP" =~ $number_re ]] ||
   ! awk -v m="$MAX_SOL" -v d="$DAILY_CAP" -v l="$DAILY_LOSS_CAP" \
     -v minimum="$LIVE_MIN_MONEY_CAP" \
     'BEGIN { exit !(m >= minimum && d >= minimum && l >= minimum) }'; then
  echo "--max-sol, --daily-cap, and --daily-loss-cap must be plain decimals at least 0.000001 with at most 9 fractional digits" >&2
  exit 1
fi
CAPS_RAISED=0
if [ "$MODE" = "live" ]; then
  if ! awk -v m="$MAX_SOL" -v d="$DAILY_CAP" -v l="$DAILY_LOSS_CAP" \
      -v mm="$LIVE_OPERATOR_MAX_SOL" -v dm="$LIVE_OPERATOR_MAX_DAILY_CAP" \
      -v lm="$LIVE_OPERATOR_MAX_DAILY_LOSS_CAP" \
      'BEGIN { exit !(m <= mm && d <= dm && l <= lm) }'; then
    # Interpolated, not spelled out: this sentence said "0.05 SOL per trade, 0.5 SOL
    # daily deploy, 0.15 SOL brake" for three literals that had already moved to
    # 0.4/1000/0.4 above it. The enforcement was always correct — only the sentence
    # lied, telling an operator the ceiling was 8x lower than it is.
    echo "live caps cannot exceed ${LIVE_OPERATOR_MAX_SOL} SOL per trade, ${LIVE_OPERATOR_MAX_DAILY_CAP} SOL daily deploy, or a ${LIVE_OPERATOR_MAX_DAILY_LOSS_CAP} SOL daily realized-loss entry brake" >&2
    exit 1
  fi
  if awk -v m="$MAX_SOL" -v d="$DAILY_CAP" -v l="$DAILY_LOSS_CAP" \
      -v cm="$LIVE_CANARY_MAX_SOL" -v cd="$LIVE_CANARY_DAILY_CAP" \
      -v cl="$LIVE_CANARY_DAILY_LOSS_CAP" \
      'BEGIN { exit !(m > cm || d > cd || l > cl) }'; then
    CAPS_RAISED=1
    if [ "$MAX_SOL_SET" -ne 1 ] || [ "$DAILY_CAP_SET" -ne 1 ] || [ "$DAILY_LOSS_CAP_SET" -ne 1 ]; then
      echo "raising any live cap requires --max-sol, --daily-cap, and --daily-loss-cap together" >&2
      exit 1
    fi
  fi
fi
if ! awk -v m="$MAX_SOL" -v d="$DAILY_CAP" 'BEGIN { exit !(m <= d) }'; then
  echo "--daily-cap must be greater than or equal to --max-sol" >&2
  exit 1
fi
# END LIVE_CAPS_VALIDATOR

validate_https_endpoint() {
  local label="$1" endpoint="$2"
  case "$endpoint" in https://*) ;; *) echo "$label must use https" >&2; exit 1;; esac
  case "$endpoint" in *$'\n'*|*$'\r'*) echo "$label cannot contain newlines" >&2; exit 1;; esac
}

validate_https_endpoint "API endpoint" "$API"
validate_https_endpoint "static endpoint" "$STATIC"
if [ -n "$RPC" ]; then validate_https_endpoint "primary RPC" "$RPC"; fi
if [ -n "$SECONDARY_RPC" ]; then validate_https_endpoint "secondary RPC" "$SECONDARY_RPC"; fi

if [ "$MODE" = "live" ]; then
  # Same bash-3.2 rule as cred_check_rpc above, and for the same two reasons: the
  # expansion does not exist on a stock Mac, and the endpoint must never become
  # another process's argv. printf is a builtin; tr only ever sees its patterns.
  rpc_lower="$(printf '%s' "$RPC" | tr '[:upper:]' '[:lower:]')"
  secondary_lower="$(printf '%s' "$SECONDARY_RPC" | tr '[:upper:]' '[:lower:]')"
  if [[ "$rpc_lower" =~ api\.mainnet-beta\.solana\.com ]] ||
     [[ "$secondary_lower" =~ api\.mainnet-beta\.solana\.com ]]; then
    echo "public Solana RPC is not accepted for either live endpoint; use two private providers" >&2
    exit 1
  fi
fi

if [ "$MODE" = "live" ]; then
  PRIMARY_RPC="$RPC" SECONDARY_RPC_VALUE="$SECONDARY_RPC" node - <<'NODE'
const primary = new URL(process.env.PRIMARY_RPC);
const secondary = new URL(process.env.SECONDARY_RPC_VALUE);
const host = (url) => url.hostname.toLowerCase().replace(/[.]$/, "");
if (primary.protocol !== "https:" || secondary.protocol !== "https:") {
  console.error("both live RPC endpoints must use HTTPS");
  process.exit(1);
}
if (host(primary) === host(secondary)) {
  console.error("--secondary-rpc must use an independent provider hostname from --rpc");
  process.exit(1);
}
NODE
fi

# BEGIN DARWIN_ACTIVATION
# The macOS half of the install. Everything above this point is shared with Linux and
# has already happened in the same order and with the same guarantees: Node verified
# or privately bootstrapped, the install directory created, the burner generated
# locally at mode 0600, the feed secret read hidden from /dev/tty, the environment
# written 0600, the release staged and per-file checked.
#
# What is left is adoption, and it is DELEGATED, not reimplemented. macos-release.sh
# and macos-launchagent.sh are the battle-tested scripts this project already runs in
# production; they carry validation this installer must not restate in a second,
# drifting copy. This block's only jobs are to hand them ABSOLUTE paths and to call
# them in the right order.
#
# Absolute paths are not a style preference. macos-release.sh refuses a relative
# --env-file or --legacy-workdir outright, and the reason it does is an incident in
# this repo: relative arguments resolved against whatever directory the caller
# happened to be in, and the "protected environment" that got normalized was not the
# one anybody meant. Every path below is checked for a leading / before it is passed.
darwin_require_absolute() {
  local label="$1" value="$2"
  case "$value" in
    /*) ;;
    *) echo "$label must be an absolute path (got: ${value:-<empty>})" >&2; return 1;;
  esac
}

# Read-only. An install that overwrites the protected environment of an executor that
# is CURRENTLY RUNNING would point a live process at a new wallet and a new journal
# mid-flight. macos-launchagent.sh refuses to install over a loaded agent, but by then
# this installer has already replaced the environment file — so the refusal has to
# happen here, before anything is created. `launchctl` is resolved through PATH rather
# than as /bin/launchctl so the regression suite can interpose a recorder and prove
# this installer never reaches the real launchd.
darwin_preflight_label() {
  local label="$1"
  command -v launchctl >/dev/null 2>&1 || return 0
  if launchctl print "gui/$(id -u)/$label" >/dev/null 2>&1; then
    cat >&2 <<AGENT

A WALL-ST-E LaunchAgent ($label) is already loaded on this Mac.

Installing over it would repoint a running executor at a new wallet and a new
journal while it is mid-flight, so nothing has been created or changed. Stop it
deliberately first, then run this installer again:

    launchctl print gui/\$(id -u)/$label      # see what is running
    bash ~/claudeco-executor/current/macos-launchagent.sh unload

If that agent is somebody else's install on a shared Mac, do not unload it.
AGENT
    return 1
  fi
  return 0
}

darwin_activate() {
  local release_dir="$1" env_file="$2" workdir="$3" commit="$4" mode="$5"
  local versioned_dir="$6" source_dir="$7"
  local controller="$release_dir/macos-launchagent.sh"
  darwin_require_absolute "the staged release" "$release_dir" || return 1
  darwin_require_absolute "--env-file" "$env_file" || return 1
  darwin_require_absolute "--legacy-workdir" "$workdir" || return 1
  if [ ! -f "$controller" ]; then
    echo "the staged release does not contain macos-launchagent.sh" >&2
    return 1
  fi

  # macos-release.sh is the VERSIONED-UPGRADE path, and it gates on a LIVE
  # environment. Measured 2026-09-06 by running its validator against a freshly
  # written dry-run environment, it aborts with exactly:
  #     versioned live adoption requires EXECUTE=1
  # and then goes on to demand LIVE_TRADING_ACK, JUPITER_API_KEY, SOLANA_RPC and
  # SOLANA_RPC_SECONDARY. A default install has none of those by design, and
  # manufacturing them to satisfy a validator would forge the very ceremony that
  # keeps one click from becoming one trade. So the dry run adopts the staged
  # release through the LaunchAgent controller directly, and macos-release.sh is
  # invoked for exactly the case it was written for: a pinned checkout adopted live.
  if [ "$mode" = "live" ] && [ -n "$source_dir" ] && [ -f "$source_dir/macos-release.sh" ]; then
    darwin_require_absolute "--releases-dir" "$versioned_dir" || return 1
    darwin_require_absolute "the pinned checkout" "$source_dir" || return 1
    # macos-release.sh checks this too. Checking it first means a malformed commit is
    # refused before the entry-pause sentinel below is created.
    if ! [[ "$commit" =~ ^[0-9a-f]{40}$ ]]; then
      echo "versioned macOS adoption needs the exact 40-character published commit" >&2
      return 1
    fi
    # The entry-pause sentinel is a precondition of the versioned install, not a
    # decoration: update-upgrade-env runs with requirePaused, so an unpaused host is
    # refused. Creating it here means the newly adopted release comes up with entries
    # paused and the operator lifts it as a separate, visible act.
    install -m 600 /dev/null "$PAUSE_FILE" 2>/dev/null || : > "$PAUSE_FILE"
    chmod 600 "$PAUSE_FILE"
    echo "▶ staging and verifying the pinned release with macos-release.sh…"
    bash "$source_dir/macos-release.sh" stage \
      --expected-commit "$commit" \
      --env-file "$env_file" \
      --legacy-workdir "$workdir" \
      --releases-dir "$versioned_dir" || return 1
    echo "▶ binding the stopped executor to that release with macos-release.sh…"
    bash "$source_dir/macos-release.sh" install \
      --expected-commit "$commit" \
      --env-file "$env_file" \
      --legacy-workdir "$workdir" \
      --release-dir "$versioned_dir/$commit" || return 1
    # macos-release.sh install has already run the controller's own install command
    # against the versioned release, so the agent to load is that one, not the staged
    # copy this installer built.
    release_dir="$versioned_dir/$commit/executor"
    controller="$release_dir/macos-launchagent.sh"
  else
    echo "▶ installing the LaunchAgent from the staged release (disabled, not started)…"
    bash "$controller" install \
      --executor-dir "$release_dir" \
      --env-file "$env_file" || return 1
  fi

  # The rollback boundary, in the same place and for the same reason as the systemd
  # path's: installing a plist starts nothing, so everything above may still be undone.
  # `load` starts a process that can reconcile or submit durable chain state, and from
  # that instant no later shell failure may restore an older journal.
  ACTIVATION_COMMITTED=1
  echo "▶ loading the LaunchAgent…"
  bash "$controller" load \
    --executor-dir "$release_dir" \
    --env-file "$env_file" || return 1
  DARWIN_EXECUTOR_DIR="$release_dir"
  return 0
}
# END DARWIN_ACTIVATION

if [ "$PLATFORM" = "darwin" ]; then
  darwin_preflight_label "$LAUNCHD_LABEL" || exit 1
fi

mkdir -p "$INSTALL_DIR" "$RELEASES_DIR"
chmod 700 "$INSTALL_DIR"
chmod 700 "$RELEASES_DIR"
if [ -e "$CURRENT_LINK" ] && [ ! -L "$CURRENT_LINK" ]; then
  echo "$CURRENT_LINK exists but is not a symlink; refusing an unsafe in-place upgrade" >&2
  exit 1
fi

STAGE_DIR="$(mktemp -d "$RELEASES_DIR/.staging.XXXXXXXX")"
RELEASE_DIR=""
ENV_NEXT="$INSTALL_DIR/.cc-executor.env.next.$$"
UNIT_NEXT="$INSTALL_DIR/.cc-executor.service.next.$$"
ENV_BACKUP="$INSTALL_DIR/.cc-executor.env.previous.$$"
UNIT_BACKUP="$INSTALL_DIR/.cc-executor.service.previous.$$"
STATE_BACKUP="$INSTALL_DIR/.cc-executor.sqlite.previous.$$"
LINK_NEXT="$INSTALL_DIR/.current.next.$$"
LINK_RESTORE="$INSTALL_DIR/.current.restore.$$"
SERVICE_WAS_ACTIVE=0
SERVICE_WAS_ENABLED=0
SERVICE_STOPPED=0
ENV_ACTIVATED=0
CURRENT_ACTIVATED=0
SERVICE_UPDATED=0
SERVICE_ENABLE_CHANGED=0
ACTIVATION_COMMITTED=0
STATE_HAD_FILE=0
STATE_PREPARED=0
ENV_HAD_FILE=0
UNIT_HAD_FILE=0
CURRENT_HAD_LINK=0
OLD_CURRENT_TARGET=""

rollback_install() {
  local status="$?"
  trap - EXIT
  if [ "$status" -ne 0 ] && [ "$ACTIVATION_COMMITTED" -eq 0 ]; then
    echo "installation failed; restoring the previous executor release" >&2
    set +e
    # macOS never reaches a systemctl or a sudo. The LaunchAgent is loaded by
    # macos-launchagent.sh as the very last act, and that script carries its own
    # verified rollback (disable, bootout, confirm) for a load that does not prove
    # readiness — so there is nothing here for this handler to undo, and calling
    # launchctl from a failed installer could only fight it.
    if [ "$PLATFORM" = "linux" ] &&
       { [ "$SERVICE_UPDATED" -eq 1 ] || [ "$CURRENT_ACTIVATED" -eq 1 ]; }; then
      sudo systemctl stop cc-executor >/dev/null 2>&1
    fi
    if [ "$SERVICE_UPDATED" -eq 1 ]; then
      if [ "$UNIT_HAD_FILE" -eq 1 ]; then
        sudo install -m 0644 "$UNIT_BACKUP" "$SERVICE_FILE"
      else
        sudo rm -f "$SERVICE_FILE"
      fi
    fi
    if [ "$CURRENT_ACTIVATED" -eq 1 ]; then
      if [ "$CURRENT_HAD_LINK" -eq 1 ]; then
        ln -s "$OLD_CURRENT_TARGET" "$LINK_RESTORE"
        activate_symlink "$LINK_RESTORE" "$CURRENT_LINK"
      else
        rm -f "$CURRENT_LINK"
      fi
    fi
    if [ "$ENV_ACTIVATED" -eq 1 ]; then
      if [ "$ENV_HAD_FILE" -eq 1 ]; then
        mv -f "$ENV_BACKUP" "$ENV_FILE"
      else
        rm -f "$ENV_FILE"
      fi
    fi
    if [ "$STATE_PREPARED" -eq 1 ]; then
      if [ "$STATE_HAD_FILE" -eq 1 ] && [ -f "$STATE_BACKUP" ]; then
        rm -f "$STATE_DB-wal" "$STATE_DB-shm"
        cp -p "$STATE_BACKUP" "$STATE_DB"
      elif [ "$STATE_HAD_FILE" -eq 0 ]; then
        rm -f "$STATE_DB" "$STATE_DB-wal" "$STATE_DB-shm"
      fi
    fi
    if [ "$PLATFORM" = "linux" ]; then sudo systemctl daemon-reload >/dev/null 2>&1; fi
    if [ "$SERVICE_ENABLE_CHANGED" -eq 1 ] && [ "$SERVICE_WAS_ENABLED" -eq 0 ]; then
      sudo systemctl disable cc-executor >/dev/null 2>&1
    fi
    if [ "$SERVICE_WAS_ACTIVE" -eq 1 ]; then
      sudo systemctl restart cc-executor >/dev/null 2>&1
    fi
    set -e
  elif [ "$status" -ne 0 ]; then
    echo "installation ended after the new service start boundary; durable state was not rolled back" >&2
  fi
  rm -f "$ENV_NEXT" "$UNIT_NEXT" "$LINK_NEXT" "$LINK_RESTORE"
  rm -f "$ENV_BACKUP" "$STATE_BACKUP"
  if [ -n "$STAGE_DIR" ] && [ -d "$STAGE_DIR" ]; then rm -rf "$STAGE_DIR"; fi
  if [ "$status" -ne 0 ] && [ "$ACTIVATION_COMMITTED" -eq 0 ] &&
     [ -n "$RELEASE_DIR" ] && [ -d "$RELEASE_DIR" ]; then
    rm -rf "$RELEASE_DIR"
  fi
  if [ -f "$UNIT_BACKUP" ]; then sudo rm -f "$UNIT_BACKUP"; fi
  exit "$status"
}
trap rollback_install EXIT

echo "▶ fetching the executor and shared policy…"
RUNTIME_FILES=(poller.mjs burner-backup.mjs journal.mjs jupiter.mjs token2022.mjs balance-verification.mjs entry-quote-guard.mjs exit-trigger.mjs feed-drain.mjs sol-usd-oracle.mjs heartbeat-health.mjs sleep-assertion.mjs monitor.mjs strategy.mjs trade-policy.mjs entry-contract.mjs dexscreener-consensus.mjs desk-mirror.mjs)
SOURCE_FILES=("${RUNTIME_FILES[@]}" package.json package-lock.json)
# launchd adopts a DIRECTORY, not a command line: macos-launchagent.sh resolves
# launchd-runner.mjs and poller.mjs out of the --executor-dir it is handed, and
# launchd-runner.mjs then validates every runtime file in that directory before it
# will render a plist. So a macOS release has to carry the lifecycle scripts too, or
# the staged release is one launchd cannot supervise. macos-release.sh rides along so
# a later versioned upgrade is available from the installed release itself.
DARWIN_FILES=(launchd-runner.mjs macos-launchagent.sh macos-release.sh)
if [ "$PLATFORM" = "darwin" ]; then
  SOURCE_FILES=("${SOURCE_FILES[@]}" "${DARWIN_FILES[@]}")
fi
if [ "$MODE" = "live" ]; then
  echo "▶ staging immutable runtime blobs from commit $SOURCE_COMMIT"
  for file in "${SOURCE_FILES[@]}"; do
    git -C "$source_root" cat-file blob "$SOURCE_COMMIT:executor/$file" > "$STAGE_DIR/$file" || {
      echo "published commit is missing executor/$file" >&2
      exit 1
    }
  done
elif [ -n "$SOURCE_DIR" ]; then
  echo "▶ staging pinned runtime from $SOURCE_DIR"
  for file in "${SOURCE_FILES[@]}"; do
    if [ ! -f "$SOURCE_DIR/$file" ] || [ -L "$SOURCE_DIR/$file" ]; then
      echo "pinned source is missing a regular non-symlink $file" >&2
      exit 1
    fi
    cp "$SOURCE_DIR/$file" "$STAGE_DIR/$file"
  done
else
  echo "WARNING: remote runtime fallback is paper-mode only; use a pinned checkout for live signing" >&2
  for file in "${SOURCE_FILES[@]}"; do
    curl -fsSL "$STATIC/executor/$file" -o "$STAGE_DIR/$file" || {
      echo "could not download $file" >&2
      exit 1
    }
  done
fi
for file in "${RUNTIME_FILES[@]}"; do
  node --check "$STAGE_DIR/$file" >/dev/null 2>&1 || { echo "staged $file is not valid JS" >&2; exit 1; }
done
if [ "$PLATFORM" = "darwin" ]; then
  # The launchd runner is the process launchd actually starts. It gets the same
  # per-file parse check as the trading modules; the two .sh files are checked by
  # bash -n rather than by node.
  node --check "$STAGE_DIR/launchd-runner.mjs" >/dev/null 2>&1 ||
    { echo "staged launchd-runner.mjs is not valid JS" >&2; exit 1; }
  for file in macos-launchagent.sh macos-release.sh; do
    bash -n "$STAGE_DIR/$file" >/dev/null 2>&1 ||
      { echo "staged $file is not valid shell" >&2; exit 1; }
  done
fi
(cd "$STAGE_DIR" && npm ci --ignore-scripts --silent >/dev/null 2>&1)
RELEASE_DIR="$RELEASES_DIR/$(date -u +%Y%m%dT%H%M%SZ)-${SOURCE_COMMIT:0:12}-$$"
mv "$STAGE_DIR" "$RELEASE_DIR"
STAGE_DIR=""

if [ ! -f "$INSTALL_DIR/burner.json" ]; then
  echo "▶ generating a dedicated, unfunded burner wallet locally…"
  (cd "$RELEASE_DIR" && BURNER_FILE="$INSTALL_DIR/burner.json" node -e 'const{Keypair}=require("@solana/web3.js");const fs=require("fs");const k=Keypair.generate();fs.writeFileSync(process.env.BURNER_FILE,JSON.stringify(Array.from(k.secretKey)),{mode:0o600})')
fi
chmod 600 "$INSTALL_DIR/burner.json"
PUBKEY="$(cd "$RELEASE_DIR" && BURNER_FILE="$INSTALL_DIR/burner.json" node -e 'const{Keypair}=require("@solana/web3.js");const fs=require("fs");console.log(Keypair.fromSecretKey(new Uint8Array(JSON.parse(fs.readFileSync(process.env.BURNER_FILE)))).publicKey.toBase58())')"

LIVE_ACK=""
LIVE_CAPS_ACK=""
EXECUTE_VALUE="0"
if [ "$MODE" = "live" ]; then
  if [ ! -r /dev/tty ]; then echo "live mode requires a terminal acknowledgement" >&2; exit 1; fi
  cat > /dev/tty <<NOTICE

WALL-ST-E LIVE CANARY
  Wallet:       $PUBKEY
  Max/trade:    $MAX_SOL SOL
  Rolling deploy: $DAILY_CAP SOL / 24h
  Realized-loss entry brake: $DAILY_LOSS_CAP SOL / rolling 24h

This is real mainnet trading from a dedicated wallet. The site cannot stop it.
Retype the public wallet above to arm this local service:
NOTICE
  IFS= read -r LIVE_ACK < /dev/tty
  if [ "$LIVE_ACK" != "$PUBKEY" ]; then echo "public-key acknowledgement did not match; live mode not armed" >&2; exit 1; fi
  if [ "$CAPS_RAISED" -eq 1 ]; then
    CAPS_ACK_EXPECTED="I acknowledge WALL-ST-E caps v2 for $PUBKEY: $MAX_SOL SOL per trade, $DAILY_CAP SOL per day, $DAILY_LOSS_CAP SOL rolling realized-loss entry brake"
    cat > /dev/tty <<NOTICE

RAISED LIVE CAPS
The canary defaults are 0.005 SOL/trade, 0.01 SOL/day deploy, and a 0.01 SOL rolling realized-loss entry brake.
To accept the higher limits above, type this entire sentence exactly:

$CAPS_ACK_EXPECTED
NOTICE
    IFS= read -r LIVE_CAPS_ACK < /dev/tty
    if [ "$LIVE_CAPS_ACK" != "$CAPS_ACK_EXPECTED" ]; then
      echo "wallet-and-cap acknowledgement did not match; raised live caps not armed" >&2
      exit 1
    fi
  fi
  EXECUTE_VALUE="1"
fi

{
  write_env_line CC_SECRET "$SECRET"
  write_env_line CC_FLOOR "$FLOOR"
  write_env_line CC_API "$API"
  write_env_line KEYPAIR "$INSTALL_DIR/burner.json"
  write_env_line STATE_DB "$STATE_DB"
  write_env_line LOCK_FILE "$LOCK_FILE"
  write_env_line PAUSE_ENTRIES_FILE "$PAUSE_FILE"
  write_env_line HARD_STOP_FILE "$HARD_STOP_FILE"
  write_env_line MAX_SOL_PER_TRADE "$MAX_SOL"
  write_env_line DAILY_SOL_CAP "$DAILY_CAP"
  write_env_line DAILY_LOSS_LIMIT_SOL "$DAILY_LOSS_CAP"
  write_env_line EXECUTE "$EXECUTE_VALUE"
  write_env_line EXECUTOR_SOURCE_COMMIT "$SOURCE_COMMIT"
  if [ "$MODE" = "live" ]; then
    write_env_line LIVE_TRADING_ACK "$LIVE_ACK"
    write_env_line LIVE_CAPS_ACK "$LIVE_CAPS_ACK"
    write_env_line JUPITER_API_KEY "$JUPITER_KEY"
    write_env_line SOLANA_RPC "$RPC"
    write_env_line SOLANA_RPC_SECONDARY "$SECONDARY_RPC"
  elif [ -n "$RPC" ]; then
    write_env_line SOLANA_RPC "$RPC"
    if [ -n "$SECONDARY_RPC" ]; then write_env_line SOLANA_RPC_SECONDARY "$SECONDARY_RPC"; fi
  fi
} > "$ENV_NEXT"
chmod 600 "$ENV_NEXT"

# Validate the complete staged release before stopping an existing executor. From
# this point onward every mutation has a rollback copy and the old process is kept
# stopped until journal initialization, symlink activation and service restart all
# succeed.
if [ "$PLATFORM" = "linux" ]; then
  if systemctl is-active --quiet cc-executor; then
    SERVICE_WAS_ACTIVE=1
    sudo systemctl stop cc-executor
    SERVICE_STOPPED=1
  fi
  if systemctl is-enabled --quiet cc-executor 2>/dev/null; then SERVICE_WAS_ENABLED=1; fi
fi
if [ -L "$CURRENT_LINK" ]; then
  CURRENT_HAD_LINK=1
  OLD_CURRENT_TARGET="$(readlink "$CURRENT_LINK")"
fi
if [ -f "$ENV_FILE" ]; then
  ENV_HAD_FILE=1
  cp -p "$ENV_FILE" "$ENV_BACKUP"
fi
if [ "$PLATFORM" = "linux" ] && sudo test -f "$SERVICE_FILE"; then
  UNIT_HAD_FILE=1
  sudo cp -p "$SERVICE_FILE" "$UNIT_BACKUP"
fi
if [ -f "$STATE_DB" ]; then
  STATE_HAD_FILE=1
  STATE_DB_PATH="$STATE_DB" node - <<'NODE'
const { DatabaseSync } = require("node:sqlite");
const db = new DatabaseSync(process.env.STATE_DB_PATH);
db.exec("PRAGMA wal_checkpoint(TRUNCATE)");
db.close();
NODE
  cp -p "$STATE_DB" "$STATE_BACKUP"
fi
STATE_PREPARED=1

# Create and bind the durable journal before systemd starts. The one-time public-key
# acknowledgement is supplied only to this command and is not a persistent bypass.
# These quoted assignment prefixes pass literal values directly to Node; the
# generated EnvironmentFile is never sourced or evaluated as shell code.
CC_SECRET="$SECRET" \
CC_FLOOR="$FLOOR" \
CC_API="$API" \
KEYPAIR="$INSTALL_DIR/burner.json" \
STATE_DB="$STATE_DB" \
LOCK_FILE="$LOCK_FILE" \
PAUSE_ENTRIES_FILE="$PAUSE_FILE" \
HARD_STOP_FILE="$HARD_STOP_FILE" \
MAX_SOL_PER_TRADE="$MAX_SOL" \
DAILY_SOL_CAP="$DAILY_CAP" \
DAILY_LOSS_LIMIT_SOL="$DAILY_LOSS_CAP" \
EXECUTE="$EXECUTE_VALUE" \
LIVE_TRADING_ACK="$LIVE_ACK" \
LIVE_CAPS_ACK="$LIVE_CAPS_ACK" \
JUPITER_API_KEY="$JUPITER_KEY" \
SOLANA_RPC="$RPC" \
SOLANA_RPC_SECONDARY="$SECONDARY_RPC" \
LIVE_STATE_INIT_ACK="$PUBKEY" \
INIT_ONLY=1 \
node "$RELEASE_DIR/poller.mjs"
chmod 600 "$STATE_DB"

ln -s "$RELEASE_DIR" "$LINK_NEXT"
mv -f "$ENV_NEXT" "$ENV_FILE"
ENV_ACTIVATED=1
activate_symlink "$LINK_NEXT" "$CURRENT_LINK"
CURRENT_ACTIVATED=1

# NODE_BIN was already chosen above — it is either the system node this host
# already had, or the private, checksum-verified copy under $NODE_RUNTIME_DIR. The
# unit must start the same binary the release was built and checked against, so this
# is a fallback for the impossible case, not a re-resolution.
if [ -z "${NODE_BIN:-}" ]; then NODE_BIN="$(command -v node)"; fi
SERVICE_USER="$(id -un)"
DARWIN_EXECUTOR_DIR=""

if [ "$PLATFORM" = "darwin" ]; then
  darwin_activate "$RELEASE_DIR" "$ENV_FILE" "$INSTALL_DIR" "$SOURCE_COMMIT" "$MODE" \
    "$VERSIONED_RELEASES_DIR" "$SOURCE_DIR"
else
# THIS MUST STAY A SYSTEM UNIT. Converting to `systemctl --user` + linger looks
# like free ergonomics — sixteen sudo lines to zero, and the unit already runs as
# User=$SERVICE_USER under $HOME — but systemd.exec(5) is explicit that
# ProtectSystem, ProtectHome, PrivateDevices, ProtectKernelTunables,
# ProtectKernelModules, ProtectKernelLogs and ProtectControlGroups "are not
# available in user services (i.e. services run by the per-user service manager)"
# because "the underlying kernel functionality is only accessible to privileged
# processes"; ReadWritePaths and PrivateTmp work there only with PrivateUsers=true
# AND unprivileged user namespaces enabled in the kernel, which an installer cannot
# assume. Every one of those appears below. A user unit would therefore run the
# process that holds a funded key with most of this sandbox silently absent, and
# would require revoking the "systemd can write only the executor directory" check
# in test-install.mjs to ship. Checked 2026-09-06 against systemd.exec(5); the cost
# is one sudo, and the ergonomic win is not worth the sandbox.
echo "▶ writing hardened systemd service…"
cat > "$UNIT_NEXT" <<UNIT
[Unit]
Description=WALL-ST-E Claude Company polling executor (floor $FLOOR, $MODE)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$CURRENT_LINK
EnvironmentFile=$ENV_FILE
ExecStart=$NODE_BIN $CURRENT_LINK/poller.mjs
Restart=always
RestartSec=5
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ReadWritePaths=$INSTALL_DIR
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
ProtectClock=true
RestrictSUIDSGID=true
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
LockPersonality=true
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
UNIT
chmod 600 "$UNIT_NEXT"
sudo install -m 0644 "$UNIT_NEXT" "$SERVICE_FILE"
SERVICE_UPDATED=1

sudo systemctl daemon-reload
sudo systemctl enable cc-executor >/dev/null 2>&1
SERVICE_ENABLE_CHANGED=1
# From this exact line forward the new process may reconcile or submit durable chain
# state. No later shell/terminal failure is allowed to restore an older SQLite snapshot,
# unit, environment, or runtime. A failed start is repaired in place under operator
# supervision; it is never made to forget what may already have happened on chain.
ACTIVATION_COMMITTED=1
sudo systemctl restart cc-executor
fi

# Only now that the new release is the running one: pruning before this point could
# delete the release a failed start still needs to roll back to.
prune_releases "$RELEASES_DIR" "$(readlink "$CURRENT_LINK" 2>/dev/null || true)" \
  "$RELEASE_DIR" "${KEEP_RELEASES:-3}"

case "$MODE" in live) MODE_BANNER="LIVE";; *) MODE_BANNER="PAPER";; esac
SECRET=""; JUPITER_KEY=""; LIVE_ACK=""; LIVE_CAPS_ACK=""; CAPS_ACK_EXPECTED=""; REPLY=""; CRED_VALUE=""
unset SECRET JUPITER_KEY LIVE_ACK LIVE_CAPS_ACK CAPS_ACK_EXPECTED REPLY CRED_VALUE

cat <<DONE

════════════════════════════════════════════════════════════════
  ✓ WALL-ST-E installed for floor $FLOOR in $MODE_BANNER mode.

  DEDICATED WALLET (PUBLIC ADDRESS):
      $PUBKEY

  Runtime commit: $SOURCE_COMMIT
  Max $MAX_SOL SOL/trade · $DAILY_CAP SOL/rolling 24h deploy
  Realized-loss entry brake $DAILY_LOSS_CAP SOL/rolling 24h
  Pause entries:  touch $PAUSE_FILE
  Hard stop:      touch $HARD_STOP_FILE
  Protected env:  $ENV_FILE
  Durable state:  $STATE_DB
DONE

if [ "$PLATFORM" = "darwin" ]; then
cat <<DONE
  Supervisor:     launchd LaunchAgent $LAUNCHD_LABEL
  Watch:          tail -f ~/Library/Logs/ClaudeCompany/wallste.stdout.log
  Status:         bash $DARWIN_EXECUTOR_DIR/macos-launchagent.sh status
  Stop process:   bash $DARWIN_EXECUTOR_DIR/macos-launchagent.sh unload
DONE
else
cat <<DONE
  Supervisor:     systemd unit cc-executor
  Watch:          sudo journalctl -u cc-executor -f
  Stop process:   sudo systemctl stop cc-executor
DONE
fi

cat <<DONE

  No wallet was funded by this installer. The private key stays at
  $INSTALL_DIR/burner.json and must never be uploaded or pasted.

  BACK IT UP BEFORE YOU FUND IT — it exists on this disk and nowhere else:
      node $CURRENT_LINK/burner-backup.mjs --out ~/wall-st-e-recovery.txt
      node $CURRENT_LINK/burner-backup.mjs --verify ~/wall-st-e-recovery.txt
  Then move that file somewhere this machine cannot reach.
  First feed connection skips historic calls and waits for the next one.
════════════════════════════════════════════════════════════════
DONE

if [ "$MODE" != "live" ]; then
cat <<DONE
  THIS IS A DRY RUN. EXECUTE=0. Nothing is signed and nothing is sent, so the
  wallet above does not need any SOL for this to run. Watch it decide for a
  while before you consider funding it.

  When you do want it to trade for real, that is a separate command you run on
  purpose, from a checkout you have reviewed — it is never this one-liner:

      git clone https://github.com/gtjvv976mb-netizen/Claude-Company.git
      cd Claude-Company && git checkout --detach <PUBLISHED_COMMIT_SHA>
      bash executor/install.sh --floor $FLOOR --live \\
        --expected-commit <PUBLISHED_COMMIT_SHA>

  It will walk you through two private RPCs and a Jupiter key, and then make you
  retype this address on the terminal before it arms:

      $PUBKEY

  Raising a cap costs a second typed sentence. Fund the wallet only once you
  have decided to do that.
════════════════════════════════════════════════════════════════
DONE
fi
